### ISSUE TITLE
High Level TODO

### ISSUE THREAD

**Issue by RoodeAwakening** [RoodeAwakening/sirHiss_Crypto#17]
Backend
- [ ] Entity Migrations
- [ ] Test via psql or postbird
- [ ] Entity Model
- [ ] Seed entity
- [ ] Entity Routes
- [ ] Test JSON endpoints
Frontend
- [ ] Entity Action Creators
- [ ] Normal Action creators + types
- [ ] Thunk Action Creators
- [ ] Entity Reducer
- [ ] Entity Components
- [ ] Frontend routes for Components
