### ISSUE TITLE
scorecard todo

### ISSUE THREAD

**Issue by RoodeAwakening** [RoodeAwakening/sirHiss_Crypto#29]
- [ ] change navbar links from deadlinks to live links
- [ ] create pages for those live links

- [ ] signup page styling
- [ ] add demo login button

- once logged in - 
- [ ] make navbar look more like Robinhood
- [ ] functionality
